- .gitignore
⛳️ **작업한 브랜치**
- fix/#5-gitignore 수정
👷 **작업한 내용**
gitignore에 .DS_Store 추가
죄송 ㅋㅋ..
|기능|스크린샷|
|:--:|:--:|
- Resolved: #5
> [Hotfix] #5- DS_Store 추가

- Winey/Common/DesignSystem/Sources/DesignSystem/Sources/NavigationBar/WINavigationBar+Height.swift
- Winey/Common/DesignSystem/Sources/DesignSystem/Sources/NavigationBar/WINavigationBar+Main.swift
- Winey/Common/DesignSystem/Sources/DesignSystem/Sources/NavigationBar/WINavigationBar.swift
- Winey/Winey/Source/Scenes/Feed/ViewController/FeedViewController.swift
- Winey/Winey/Source/Scenes/MyFeed/ViewController/MyFeedViewController.swift
⛳️ **작업한 브랜치**
- feat/#17-navigation-bar
👷 **작업한 내용**
- https://github.com/team-winey/Winey-iOS/pull/21#issue-1803778208 내용과 동일합니당
- 새벽 이슈로 인해... 죄송합니다...하하
|기능|스크린샷|
|:--:|:--:|
- Resolved: #17
> [Hotfix] 네비게이션바 구현 2 (커밋 푸쉬 못했네요. . . )

- Winey/Winey.xcodeproj/project.pbxproj
- Winey/Winey.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Winey/Winey/Source/Network/DTO/FeedLike/FeedLikeResponse.swift
- Winey/Winey/Source/Network/Service/FeedLike/FeedLikeAPI.swift
- Winey/Winey/Source/Network/Service/FeedLike/FeedLikeService.swift
- Winey/Winey/Source/Scenes/Feed/Model/FeedModel.swift
- Winey/Winey/Source/Scenes/Feed/View/FeedCell.swift
- Winey/Winey/Source/Scenes/Feed/ViewController/FeedViewController.swift
⛳️ **작업한 브랜치**
- feature/#39
👷 **작업한 내용**
피드 좋아요/취소 API 연결
헤더의 캐릭터 이미지와 레벨별 프로필 이미지는 아직 적용되지 않았습니다.
|기능|스크린샷|
|:--:|:--:|
|GIF|![Simulator Screen Recording - iPhone 14 Pro - 2023-07-19 at 19 05 56](https://github.com/team-winey/Winey-iOS/assets/83493636/28a3ee27-f485-4e94-abd7-9f67d9b97aef)|
- Resolved: #39
> [Feat] #39 - 피드 좋아요/취소 API 연결

- Winey/Winey.xcodeproj/project.pbxproj
- Winey/Winey/Source/Network/DTO/Goal/PostGoalRequest.swift
- Winey/Winey/Source/Network/DTO/Goal/PostGoalResponse.swift
- Winey/Winey/Source/Network/Service/Goal/GoalAPI.swift
- Winey/Winey/Source/Network/Service/Goal/GoalService.swift
- Winey/Winey/Source/Scenes/SaveGoal/ViewController/SaveGoalViewController.swift
⛳️ **작업한 브랜치**
- feature/#54
👷 **작업한 내용**
목표 절약 API 연결
|기능|스크린샷|
|:--:|:--:|
|GIF|![Simulator Screen Recording - iPhone 14 Pro - 2023-07-20 at 08 15 38](https://github.com/team-winey/Winey-iOS/assets/83493636/27ebcf52-c577-4222-8996-7f9d1e71a7e7)|
- Resolved: #54
> [Feat] #54 - 목표절약 API 연결

- Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/btn/btn_plus.imageset/Contents.json
- Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/btn/btn_plus.imageset/btn_plus.svg
- Winey/Common/DesignSystem/Sources/DesignSystem/Sources/Button/MIButton+Type.swift
- Winey/Common/DesignSystem/Sources/DesignSystem/Sources/Button/MIButton.swift
- Winey/Common/DesignSystem/Sources/DesignSystem/Sources/Images/UIImage+.swift
- Winey/Common/DesignSystem/Sources/DesignSystem/Sources/TextField/WITextFieldView.swift
- Winey/Winey.xcodeproj/project.pbxproj
- Winey/Winey.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- Winey/Winey/Source/Network/Service/Feed/FeedService.swift
- Winey/Winey/Source/Network/Service/FeedLike/FeedLikeAPI.swift
- Winey/Winey/Source/Scenes/Upload/View/ContentsWriteView.swift
- Winey/Winey/Source/Scenes/Upload/View/DotLayerView.swift
- Winey/Winey/Source/Scenes/Upload/View/PhotoUploadView.swift
- Winey/Winey/Source/Scenes/Upload/View/UploadBaseView.swift
- Winey/Winey/Source/Scenes/Upload/ViewController/UploadViewController.swift
⛳️ **작업한 브랜치**
- feature/#52
👷 **작업한 내용**
QA 시간에 받았던 지적사항들을 개선하였습니다
못 바꾼거 있다면 말해주세욤
|기능|스크린샷|
|:--:|:--:|
|GIF|![Simulator Screen Recording - iPhone 14 Plus - 2023-07-20 at 08 43 53](https://github.com/team-winey/Winey-iOS/assets/40496065/212eccb5-b6b5-470e-af82-4998cccb8d20)|
- Resolved: #52
> [Fix] #52 - 업로드 뷰 QA 피드백 사항 반영

- Winey/Winey.xcodeproj/project.pbxproj
- Winey/Winey/Source/Network/DTO/Recommend/TotalRecommendResponse.swift
- Winey/Winey/Source/Network/Service/FeedLike/FeedLikeAPI.swift
- Winey/Winey/Source/Network/Service/Recommend/RecommendAPI.swift
- Winey/Winey/Source/Network/Service/Recommend/RecommendService.swift
- Winey/Winey/Source/Scenes/Recommend/Model/RecommendModel.swift
- Winey/Winey/Source/Scenes/Recommend/View/RecommendCell.swift
- Winey/Winey/Source/Scenes/Recommend/ViewController/RecommendViewController.swift
⛳️ **작업한 브랜치**
- feature/#56
👷 **작업한 내용**
- 추천피드 API 연결
- 웹 뷰 연결
링크 보러가기 버튼 터치영역 수정 필요함
|기능|스크린샷|
|:--:|:--:|
|GIF|![Simulator Screen Recording - iPhone 14 Pro - 2023-07-20 at 13 15 33](https://github.com/team-winey/Winey-iOS/assets/83493636/7a6dfeb6-c6b2-40ab-ab68-afd627a6a41e)|
- Resolved: #56
> [Feat] #56 - 추천피드 API 연결

- Winey/Winey/Source/Global/Supports/SceneDelegate.swift
- Winey/Winey/Source/Scenes/Feed/Model/FeedModel.swift
- Winey/Winey/Source/Scenes/Feed/View/FeedCell.swift
- Winey/Winey/Source/Scenes/Feed/ViewController/FeedViewController.swift
- Winey/Winey/Source/Scenes/Guide/ViewControllers/GuideViewController.swift
- Winey/Winey/Source/Scenes/Guide/Views/CautionView.swift
- Winey/Winey/Source/Scenes/MyFeed/ViewController/MyFeedViewController.swift
⛳️ **작업한 브랜치**
- feature/#63
👷 **작업한 내용**
- 삭제, 신고 분기처리
- 셀 구분선 추가
- 가이드 버튼 터치 이벤트 추가
- 마이 피드 좋아요 버튼 API 연결
|기능|스크린샷|
|:--:|:--:|
|GIF|![Simulator Screen Recording - iPhone 14 Pro - 2023-07-21 at 14 01 04](https://github.com/team-winey/Winey-iOS/assets/83493636/45aac5db-b1a6-4791-a51f-acdf019089cc)|
- Resolved: #63
> [Fix] #63 - QA 피드백 반영

- Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Colors.xcassets/yellow/darkYellow.colorset/Contents.json
- Winey/Common/DesignSystem/Sources/DesignSystem/Resources/Colors.xcassets/yellow/mainYellow.colorset/Contents.json
- Winey/Common/DesignSystem/Sources/DesignSystem/Sources/Color/Pallete.swift
- Winey/Common/DesignSystem/Sources/DesignSystem/Sources/Color/UIColor+.swift
- Winey/Winey/Source/Scenes/Guide/ViewControllers/GuideViewController.swift
- Winey/Winey/Source/Scenes/Guide/Views/CautionView.swift
- Winey/Winey/Source/Scenes/Guide/Views/LevelupRuleView.swift
- Winey/Winey/Source/Scenes/MyPage/ViewControllers/MypageViewController.swift
- Winey/Winey/Source/Scenes/MyPage/Views/Cells/MypageGoalInfoCell.swift
- Winey/Winey/Source/Scenes/SaveGoal/ViewController/SaveGoalViewController.swift
⛳️ **작업한 브랜치**
- feature/#78
👷 **작업한 내용**
- 365일 이상 입력하면 목표 등록 못하게 해 줌
- 더 즐거운 위니 사용법 페이지 레이아웃 수정
레이아웃 깨지면 언제든 알려줘요
- Resolved: #78
> [Fix] #78 - 365일 제한 및 레벨업 안내뷰 밑줄 추가 

- Winey/Winey/Source/Global/Extension/Foundation+/NotificationName+.swift
- Winey/Winey/Source/Scenes/Detail/DetailMapper.swift
- Winey/Winey/Source/Scenes/Detail/DetailViewController.swift
- Winey/Winey/Source/Scenes/Detail/Views/CommentCell.swift
- Winey/Winey/Source/Scenes/Detail/Views/DetailInfoCell.swift
- Winey/Winey/Source/Scenes/Detail/Views/FloatingCommentView.swift
- Winey/Winey/Source/Scenes/Feed/View/FeedCell.swift
- Winey/Winey/Source/Scenes/Feed/ViewController/FeedViewController.swift
- Winey/Winey/Source/Scenes/TabBar/TabBarController.swift
- Winey/Winey/Source/Scenes/TabBar/TabBarItem.swift
⛳️ **작업한 브랜치**
- feat/#91-g-like-delete-api
👷 **작업한 내용**
- Resolved: #91
> [Feat] 피드 좋아요 / 삭제 기능 구현 

- Winey/Winey/Source/Scenes/Alert/View/AlertCell.swift
- Winey/Winey/Source/Scenes/Alert/ViewController/AlertViewController.swift
⛳️ **작업한 브랜치**
- feature/#129
👷 **작업한 내용**
- 닉네임에 '계급명'이 들어간 유저를 고려한 예외상황. ex) 귀족영민님이 회원님의 게시글을 좋아합니다.
변수명에 따른 이미지 변경이어서 앞선 상황을 고려하여 예외처리 코드로 재작성 하였습니다.
- 서버로 부터 넘어온 정보로 변수를 대체하는 함수인 configure 코드 일부를 첨언하였습니다.
|기능|스크린샷|
|:--:|:--:|
- Resolved: #129
> [Fix] #129 - 알림뷰 함수 수정

- Winey/Common/DesignSystem/Sources/DesignSystem/Sources/Toast/WIToast+Type.swift
- Winey/Common/DesignSystem/Sources/DesignSystem/Sources/View/WIEmptyView.swift
- Winey/Winey/Source/Network/Service/Comment/CommentService.swift
- Winey/Winey/Source/Network/Service/Feed/FeedService.swift
- Winey/Winey/Source/Scenes/Detail/DetailViewController.swift
- Winey/Winey/Source/Scenes/Feed/ViewController/FeedViewController.swift
- Winey/Winey/Source/Scenes/MyFeed/ViewController/MyFeedViewController.swift
- Winey/Winey/Source/Scenes/MyPage/ViewControllers/MypageViewController.swift
- Winey/Winey/Source/Scenes/MyPage/Views/Cells/MypageGoalInfoCell.swift
- Winey/Winey/Source/Scenes/Upload/View/ContentsWriteView.swift
- Winey/Winey/Source/Scenes/Upload/View/PriceUploadView.swift
- Winey/Winey/Source/Scenes/Upload/ViewController/UploadViewController.swift
⛳️ **작업한 브랜치**
- feature/#137
👷 **작업한 내용**
- 마이피드 삭제 시 ToastAlert 뜨게하기
- 피드 뷰에서 유저신고/본인 피드 삭제시 ToastAlert 뜨게하기
- 피드 디테일 뷰에서 유저신고/피드삭제/댓글삭제시 ToastAlert 뜨게하기
ToastAlert 적용이 안된 곳 있으면 말씀부탁!
- Resolved: #137
> [Feat] Toast Alert 필요한 곳에 모두 적용시키기

- Winey/Winey.xcodeproj/project.pbxproj
- Winey/Winey/Source/Network/DTO/Notification/CheckAllNotificationResponse.swift
- Winey/Winey/Source/Network/Service/Notification/NotificationAPI.swift
- Winey/Winey/Source/Network/Service/Notification/NotificationService.swift
- Winey/Winey/Source/Scenes/Alert/ViewController/AlertViewController.swift
⛳️ **작업한 브랜치**
- feature/#131
👷 **작업한 내용**
API 연결을 하여, 서버 측에 모든 알림이 읽혀졌을 때, 모두 읽음 처리 됨을 알리는 데이터를 전송하였습니다.
|기능|스크린샷|
|:--:|:--:|
- Resolved: #131
> [Feat] #131 - 모든 알림 읽음처리 API연결

- Winey/Winey.xcodeproj/project.pbxproj
- Winey/Winey.xcodeproj/xcshareddata/xcschemes/Winey.xcscheme
- Winey/Winey/Source/Global/Supports/AppDelegate.swift
- Winey/Winey/Source/Log/Amplitude+EventName.swift
- Winey/Winey/Source/Log/AmplitudeManager.swift
- Winey/Winey/Source/Scenes/Onboarding/OnboardingViewController.swift
⛳️ **작업한 브랜치**
- feature/#145-log
👷 **작업한 내용**
- Amplitude Log 세팅작업을 진행했어요.
- 아래처럼 사용해주세요.
```swift
let logEvent = LogEventImpl(category: .view_onboarding, parameters: ["page_number": currentPage])
AmplitudeManager.logEvent(event: logEvent)
```
- 아래 사진처럼 콘솔창 필터링해서 로그가 제대로 수집되는지 확인해주세요.
- #145
> [Setting] Amplitude Log 세팅

- Winey/Winey/Source/Scenes/Detail/DetailViewController.swift
- Winey/Winey/Source/Scenes/Login/ViewController/LoginViewController.swift
- Winey/Winey/Source/Scenes/MyPage/ViewControllers/MypageViewController.swift
- Winey/Winey/Source/Scenes/Nickname/ViewController/NicknameViewController.swift
- Winey/Winey/Source/Scenes/Onboarding/AnimationOnboardingViewController.swift
- Winey/Winey/Source/Scenes/Onboarding/OnboardingViewController.swift
- Winey/Winey/Source/Scenes/Upload/ViewController/UploadViewController.swift
⛳️ **작업한 브랜치**
- feature/#145
👷 **작업한 내용**
- [온보딩, 로그인, 온보딩 2, 닉네임, 디테일, 마이페이지, 업로드] 화면의 필요한 로그 이벤트들을 추가합니다.
- #145
> [Feat] [온보딩, 로그인, 온보딩 2, 닉네임, 디테일, 마이페이지, 업로드] 로그 추가 

- Winey/Winey/Source/Scenes/Feed/ViewController/FeedViewController.swift
- Winey/Winey/Source/Scenes/Recommend/ViewController/RecommendViewController.swift
- Winey/Winey/Source/Scenes/SaveGoal/ViewController/SaveGoalViewController.swift
⛳️ **작업한 브랜치**
- feature/#145
👷 **작업한 내용**
[목표설정, 추천, 홈피드, 홈 팝업] 로그 추가
|기능|스크린샷|
|:--:|:--:|
- Resolved: #145
> [Feat] #145 - [목표설정, 추천, 홈피드, 홈 팝업] 로그 추가

- Winey/Winey.xcodeproj/project.pbxproj
- Winey/Winey/Source/Network/DTO/Notification/CheckAllNotificationResponse.swift
- Winey/Winey/Source/Network/Service/Notification/NotificationAPI.swift
- Winey/Winey/Source/Network/Service/Notification/NotificationService.swift
- Winey/Winey/Source/Scenes/Alert/ViewController/AlertViewController.swift
⛳️ **작업한 브랜치**
- feature/#이슈번호
👷 **작업한 내용**
|기능|스크린샷|
|:--:|:--:|
- Resolved: #이슈번호
> [Merge] #141 - 브랜치 최신화

- Winey/Common/DesignSystem/Sources/DesignSystem/Sources/TextField/WITextFieldView.swift
- Winey/Winey/Source/Scenes/Detail/DetailViewController.swift
- Winey/Winey/Source/Scenes/Detail/Views/DetailInfoCell.swift
- Winey/Winey/Source/Scenes/Feed/View/FeedCell.swift
- Winey/Winey/Source/Scenes/Onboarding/AnimationOnboardingViewController.swift
⛳️ **작업한 브랜치**
- feature/#146
👷 **작업한 내용**
- Resolved: #146
> [Fix] #146 - iOS 자체 QA

- Winey/Winey/Source/Scenes/MyFeed/ViewController/MyFeedViewController.swift
- Winey/Winey/Source/Scenes/MyPage/ViewControllers/MypageViewController.swift
- Winey/Winey/Source/Scenes/MyPage/Views/Cells/MenuCell.swift
- Winey/Winey/Source/Scenes/MyPage/Views/Cells/MypageGoalInfoCell.swift
- Winey/Winey/Source/Scenes/MyPage/Views/Cells/MypageProfileCell.swift
⛳️ **작업한 브랜치**
- feature/#150
👷 **작업한 내용**
- 닉네임 변경 버튼 위치 조정
- 마이피드뷰에서 피드 터치 시, 디테일뷰로 화면 이동 
- 마이페이지 각 셀들 영역 간, 구분선 긋기를 진행하였습니다.
QA 보완 완료했습니다!
|기능|스크린샷|
|:--:|:--:|
|GIF|![Simulator Screen Recording - iPhone 14 Pro - 2023-08-25 at 01 57 25](https://github.com/team-winey/Winey-iOS/assets/105866831/feca41a9-8e80-4239-bc85-3c5767f2b005)|
- Resolved: #150
> [Fix] #150 - iOS 자체 QA

- Winey/Winey/Source/Scenes/Feed/ViewController/FeedViewController.swift
- Winey/Winey/Source/Scenes/Nickname/ViewController/NicknameViewController.swift
⛳️ **작업한 브랜치**
- feature/#174
👷 **작업한 내용**
제발 더이상 이슈가 발생하지 않았으면 제발 더이상 이슈가 발생하지 않았으면 제발 더이상 이슈가 발생하지 않았으면 제발 더이상 이슈가 발생하지 않았으면 제발 더이상 이슈가 발생하지 않았으면 제발 더이상 이슈가 발생하지 않았으면 
혹시나 마지막까지 이슈 나올지도 모르니까 테플 직전에 이슈 닫을게요.
https://github.com/team-winey/Winey-iOS/assets/83493636/47b89bac-43a0-4045-8bff-5e8ad900046c
- Resolved: #174
> [Fix] #174 - 1차 릴리즈 전 마지막 QA처리

- Winey/Winey/Source/Scenes/Feed/ViewController/FeedViewController.swift
⛳️ **작업한 브랜치**
- feature/#182
👷 **작업한 내용**
신고하기 구글폼링크 연결했습니다
이상하면 알려주세요
용량이슈...
- Resolved: #182
> [Add] #182 - 구글폼 링크 연결

- Winey/Winey/Source/Scenes/Detail/DetailViewController.swift
⛳️ **작업한 브랜치**
- feature/#189
👷 **작업한 내용**
피드 상세뷰에 신고하기 메커니즘 적용
안되면 말해주세용
- Resolved: #189
> [Fix] #189 - 피드상세뷰에 신고하기 메커니즘 적용

- Winey/Common/DesignSystem/Sources/DesignSystem/Sources/TextField/WITextFieldView.swift
- Winey/Winey/Source/Global/Utils/PhotoManager.swift
- Winey/Winey/Source/Network/Service/Recommend/RecommendService.swift
- Winey/Winey/Source/Scenes/Nickname/ViewController/NicknameViewController.swift
- Winey/Winey/Source/Scenes/Recommend/ViewController/RecommendViewController.swift
⛳️ **작업한 브랜치**
- feature/#193
👷 **작업한 내용**
- 천지인 키보드 사용시 가운데 점 입력 허용
- 텍스트필드 공백 입력 방지
- 추천 절약법 URL이 null 값인 데이터 필터링
- URL에 한글 들어가 있을 때 별도 인코딩처리
안되면 말해주세용
흑 나가 봐야해서,, 브랜치 받아서 한번씩 돌려봐줘요 ㅠ 
- Resolved: #193
> [Fix] #193 - 최종점검(2차)

- Winey/Winey.xcodeproj/project.pbxproj
- Winey/Winey/Source/Network/Base/CustomMoyaProvider.swift
- Winey/Winey/Source/Network/Base/FeedAPI.swift
- Winey/Winey/Source/Network/Service/Comment/CommentAPI.swift
- Winey/Winey/Source/Network/Service/Feed/FeedService.swift
- Winey/Winey/Source/Network/Service/FeedLike/FeedLikeAPI.swift
- Winey/Winey/Source/Network/Service/Goal/GoalAPI.swift
- Winey/Winey/Source/Network/Service/Login/SessionInterceptor.swift
- Winey/Winey/Source/Network/Service/Nickname/NicknameAPI.swift
- Winey/Winey/Source/Network/Service/Notification/NotificationAPI.swift
- Winey/Winey/Source/Network/Service/Recommend/RecommendAPI.swift
- Winey/Winey/Source/Network/Service/User/UserAPI.swift
- Winey/Winey/Source/Scenes/Feed/ViewController/FeedViewController.swift
⛳️ **작업한 브랜치**
- feature/#193
👷 **작업한 내용**
- 인터셉터 코드 전면 제거
- 기간 내에 목표 달성하면 목표 재설정하게끔 유도하는 로직 추가
- 회원탈퇴/로그아웃 후에 재로그인하면 낡은 토큰이 헤더에 실리는 오류 수정
버그 발견시 제보바람
- Resolved: #193
> [Fix] #193 - 최종점검2
